name: Build and Deploy to GitHub Pages

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  deploy:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-gh-pages-deployment.yml@59-fix-github-pages-deployment-for-nachet-backend
    with:
      node-version: 18
      publish-dir: ./build
      cache-dependency-path: .
    secrets: inherit
